In [1]:
from keras.backend import one_hot

In [4]:
import numpy as np

In [12]:
import tensorflow as tf

In [13]:
devel_ts = tf.convert_to_tensor(devel)

In [17]:
label_onehot = one_hot(devel_ts,2)

In [18]:
from keras import backend as K

In [20]:
devel_one_hot = K.eval(label_onehot)

In [24]:
from sklearn.metrics import roc_curve, roc_auc_score

In [33]:
pred = np.zeros_like(devel_one_hot)

In [44]:
pred[:,0] = np.random.random(size=devel_one_hot.shape[0])
pred[:,1] = 1 - pred[:,0]

In [47]:
y_true = devel_one_hot
y_pred = pred

In [ ]:
from sklearn.metrics import 

In [57]:
roc_auc_score(y_true[:,1],y_pred[:,1])

0.5118288888888889

In [ ]:
far, tpr, thd = roc_curve(y_true,pred,pos_label=y_true[5])

In [ ]:
import numpy as np

In [ ]:
np.argmax(pred,axis=1).shape

In [8]:
import pandas as pd
from tfrecord_server import _pd_shuffle

In [89]:
df = pd.read_csv('baseline/frames-4/frames_4_interval_1.csv')
devel =_pd_shuffle(df,'devel')

In [93]:
one_hot_devel = np.eye(2)[devel]

In [96]:
devel_tf = tf.convert_to_tensor(devel)
one_hot_devel_tf = K.eval(K.one_hot(devel_tf,2))

In [138]:
max_idxs = np.argmax(y_pred,axis=1)

In [144]:
max_value_of_idxs = np.asarray([y_pred[i,max_idxs[i]] for i in range(len(max_idxs))])

In [158]:
from sklearn.metrics import roc_auc_score

In [172]:
y_true[:,1][np.where(np.argmax(y_true,axis=1)==0)[0]]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [174]:
y_true[:,1]

array([1., 1., 0., ..., 1., 1., 1.], dtype=float32)

In [190]:
from sklearn.metrics import accuracy_score, log_loss

In [195]:
y_true

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [196]:
y_pred

array([[0.19690786, 0.8030921 ],
       [0.63775945, 0.36224055],
       [0.53394043, 0.46605957],
       ...,
       [0.5882181 , 0.4117819 ],
       [0.07252378, 0.9274762 ],
       [0.08540457, 0.9145954 ]], dtype=float32)

# compare loss and accuracy functions in sklearn and keras(tf)

In [241]:
import keras
import sklearn

In [255]:
true_single_tf = tf.convert_to_tensor(np.argmax(y_true,axis=1))
pred_single_tf = tf.convert_to_tensor(np.argmax(y_pred,axis=1))
true_single_tf_amax = tf.cast(true_single_tf,tf.float32)
pred_single_tf_amax = tf.convert_to_tensor(np.amax(y_pred,axis=1))

true_tf = tf.convert_to_tensor(y_true)
pred_tf = tf.convert_to_tensor(y_pred)

In [244]:
# sklearn binary acc
sklearn.metrics.accuracy_score(np.argmax(y_true,axis=1),np.argmax(y_pred,axis=1))

0.50875

In [246]:
# tf binary acc
keras.backend.eval(keras.metrics.binary_accuracy(true_single_tf,pred_single_tf))

0.50875

In [247]:
# sklearn binary loss
sklearn.metrics.log_loss(np.argmax(y_true,axis=1),np.amax(y_pred,axis=1))

0.526635501720759

In [256]:
#tf binary loss
keras.backend.eval(keras.metrics.binary_crossentropy(true_single_tf_amax,pred_single_tf_amax))

0.52663547

In [262]:
# sklearn categorical accuracy !!!!!!!!!!!!!!note 只接受1-d的array 这里测试了一下balanced的结果 不做评价
sklearn.metrics.balanced_accuracy_score(np.argmax(y_true,axis=1),np.argmax(y_pred,axis=1))

0.5145833333333334

In [265]:
# tf categorical accuracy
keras.backend.eval(tf.reduce_mean(keras.metrics.categorical_accuracy(true_tf,pred_tf)))

0.50875

In [267]:
# sklearn categorical loss
sklearn.metrics.log_loss(y_true,y_pred)

0.9911700848661975

In [270]:
# tf categorical loss
keras.backend.eval(tf.reduce_mean(keras.metrics.categorical_crossentropy(true_tf,pred_tf)))

0.99117

## summary
使用sklearn和TensorFlow计算准确率和损失得出的结论大致一样，所以在callbacks里可以放心使用sklearn的API

In [110]:
np.argmax(one_hot_devel_tf,axis=1)

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [ ]:
eer(devel,pred[:,0])

In [1]:
from tfrecord_server import decode_tfrecord

In [41]:
filenames,batch_size=32,normalize_method=2,perform_shuffle=False,repeat_count=None,one_hot=False,n_class=2

SyntaxError: can't assign to literal (<ipython-input-41-0225eaa13472>, line 1)

In [5]:
import tensorflow as tf
from tfrecord_server import decode_tfrecord
from model import Arch
from keras.layers import Input
from keras.optimizers import Adam

In [7]:
images, labels = decode_tfrecord('./baseline/frames-12/tfrcd/frames-12-devel-interval-1-7200.tfrecord',one_hot=False,n_class=2)
m = Arch(model_input=Input(tensor=images),classes=1,theta=0)
m.compile(optimizer=Adam(),loss='binary_crossentropy',metrics=['acc'],target_tensors=labels)
steps = 7200//32

In [8]:
eval_results = m.evaluate(None,None,steps=steps,verbose=1)

225/225 [==============================] - ETA: 22:2 - ETA: 11:4 - ETA: 8:1 - ETA: 6: - ETA: 5: - ETA: 4: - ETA: 4: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 3: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 2: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 59s - ETA: 59 - ETA: 58 - ETA: 58 - ETA: 57 - ETA: 57 - ETA: 56 - ETA: 56 - ETA: 55 - ETA: 55 - ETA: 54 - E

In [9]:
y_pred = m.predict(None,None,steps=steps,verbose=1)

225/225 [==============================] - ETA: 2: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 1: - ETA: 59s - ETA: 59 - ETA: 59 - ETA: 58 - ETA: 58 - ETA: 58 - ETA: 57 - ETA: 57 - ETA: 56 - ETA: 56 - ETA: 56 - ETA: 55 - ETA: 55 - ETA: 55 - ETA: 54 - ETA: 54 - ETA: 54 - ETA: 53 - ETA: 53 - ETA: 52 - ETA: 52 - ETA: 52 - ETA: 51 - ETA: 51 - ETA: 51 - ETA: 50 - ETA: 50 - ETA: 50 - ETA: 49 - ETA: 49 - ETA: 49 - ETA: 48 - ETA: 48 - ETA: 48 - ETA: 47 - ETA: 47 - ETA: 46 - ETA: 46 - ETA: 46 - ETA: 45 - ETA: 45 - ETA: 4

In [12]:
import pandas as pd
from tfrecord_server import _pd_shuffle

In [13]:
df = pd.read_csv('baseline/frames-4/frames_4_interval_1.csv')
y_true = _pd_shuffle(df,'devel')

In [ ]:
import pandas

In [ ]:
import warnings
warnings.simplefilter('ignore')

%run train -conf ./baseline/configs/frames-4-depth-3.ini